/ekf_imu_gps:
  ros__parameters:
    # Marco de referencia
    #map_frame: map
    #odom_frame: odom
    #base_link_frame: base_link
    #world_frame: map

    #frequency: 30
    #two_d_mode: true
    #sensor_timeout: 0.1
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    # Configuraci贸n del IMU
    imu0: /imu/data
    imu0_config: [false, false, false,   # X, Y, Z (posici贸n)
                  true, true, true,      # Roll, Pitch, Yaw (orientaci贸n)
                  false, false, false,   # Velocidades angulares (X, Y, Z) - giroscopio
                  true, true, true,      # Velocidades Roll, Pitch, Yaw
                  true, true, true,      # Aceleraciones lineales (X, Y, Z) - aceler贸metro
                  false, false, false]   # Aceleraciones Roll, Pitch, Yaw

   
