/ekf_filter_node:
  ros__parameters:
    # Marco de referencia
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # Configuración de la odometría
    odometry0: /odometry/simulated  # Tópico de odometría simulada
    odometry0_config: [false, false, false,  # X, Y, Z
                       false, false, false, # Roll, Pitch, Yaw
                       false, false, false, # Velocidades X, Y, Z
                       false, false, false, # Velocidades Roll, Pitch, Yaw
                       false, false, false, # Aceleraciones X, Y, Z
                       false, false, false] # Aceleraciones Roll, Pitch, Yaw

    # Configuración del IMU
    imu0: /imu/data
    imu0_config: [false, false, false,   # X, Y, Z
                  false, false, false,   # Roll, Pitch, Yaw
                  true, true, true,   # Velocidades X, Y, Z
                  false, false, false,      # Velocidades Roll, Pitch, Yaw
                  true, true, true,      # Aceleraciones X, Y, Z
                  false, false, false]      # Aceleraciones Roll, Pitch, Yaw

    # Configuración del GPS
    gps0: /gps/fix
    gps0_config: [true, true, true,      # X, Y, Z
                  false, false, false,   # Roll, Pitch, Yaw
                  false, false, false,   # Velocidades X, Y, Z
                  false, false, false,   # Velocidades Roll, Pitch, Yaw
                  false, false, false,   # Aceleraciones X, Y, Z
                  false, false, false]   # Aceleraciones Roll, Pitch, Yaw

    # Covarianza
    process_noise_covariance: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                               0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
                               0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
                               0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
                               0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
                               0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
