/navsat_gps:
  ros__parameters:
    # Marco de referencia
    #map_frame: map
    #odom_frame: odom
    #base_link_frame: base_link
    #world_frame: map
    #navsat_gps: navsat_gps

    #frequency: 30
    #two_d_mode: true
    #sensor_timeout: 0.1
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link #base_link/odom/map
    world_frame: odom
    #navsat_gps: navsat_gps
    
    # Configuración del GPS
    gps0: /gps/fix
    gps0_config: [true, true, true,      # X, Y, Z (posición)
                  false, false, false,   # Roll, Pitch, Yaw
                  false, false, false,   # Velocidades X, Y, Z
                  false, false, false,   # Velocidades Roll, Pitch, Yaw
                  false, false, false,   # Aceleraciones X, Y, Z
                  false, false, false]   # Aceleraciones Roll, Pitch, Yaw

    # Covarianza
    process_noise_covariance: [2.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                               0.0, 2.0, 0.0, 0.0, 0.0, 0.0,
                               0.0, 0.0, 2.0, 0.0, 0.0, 0.0,
                               0.0, 0.0, 0.0, 2.0, 0.0, 0.0,
                               0.0, 0.0, 0.0, 0.0, 2.0, 0.0,
                               0.0, 0.0, 0.0, 0.0, 0.0, 2.0]