/robot:
  ros__parameters:
    odom_frequency: 10
    port_md: /dev/ttyACM2
    type_robot: R2D2-02
    gains: [5.5, 4.6]
    enable: True

/robot2:
  ros__parameters:
    odom_frequency: 30
    port_md: /dev/ttyACM4
    type_robot: R2D2-01
    gains: [15.5, 16.6]
    enable: True